USE StudentDB;
GO

-- Додаємо 4 поля аудиту в інші таблиці бази даних
ALTER TABLE [Bratkovskiy].Room ADD UCR NVARCHAR(50), DCR DATETIME, ULC NVARCHAR(50), DLC DATETIME;
ALTER TABLE [Bratkovskiy].Hobby ADD UCR NVARCHAR(50), DCR DATETIME, ULC NVARCHAR(50), DLC DATETIME;
ALTER TABLE [Bratkovskiy].Exam ADD UCR NVARCHAR(50), DCR DATETIME, ULC NVARCHAR(50), DLC DATETIME;
ALTER TABLE [Bratkovskiy].Teacher ADD UCR NVARCHAR(50), DCR DATETIME, ULC NVARCHAR(50), DLC DATETIME;
-- і так далі...
GO